# Generated by Django 3.1 on 2020-09-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approve_comment',
            field=models.BooleanField(default=True),
        ),
    ]
